### ISSUE TITLE
Remote-XUL-Manager doesn't work in Firefox 50.*

### ISSUE THREAD

**Issue by rednaxela-alexander** [jvillalobos/Remote-XUL-Manager#21]
Hello, i'm having problems with xul manager in Firefox 50.*, i think is the new version becouse i downgrade to 49.* version and works perfectly, i can add new domains and open new windows but de menus does not work, please help

**Comment by jvillalobos** [comment]
If the remote XUL page opens, then the add-on is doing its job. Something broken inside the page could mean that something changed in Firefox 50 with regards to XUL that the website hasn't adapted to, and it isn't something I can fix in the add-on. If there's a public page where I can test this, I can confirm it for you.

**Comment by rednaxela-alexander** [comment]
I use XUL to open Enterprise Performance Manager (Hyperion Workspace) a product from Oracle, and all of users have the same isue, i saw a part in the code when in set as maxversion to 49. in this page, but i don't know if is this the reason:
    
    <em:targetApplication>
      <Description>
        <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
        <em:minVersion>42.0</em:minVersion>
        <em:maxVersion>49.*</em:maxVersion>
      </Description>
</em:targetApplication>

**Comment by jvillalobos** [comment]
That shouldn't be a problem. Firefox ignores the `maxVersion`, and it would be completely disabled if Firefox determined it was incompatible.

**Comment by rajneesh75** [comment]
Hi rednaxela-alexander

Are you having the same issue that is mentioned here
https://github.com/jvillalobos/Remote-XUL-Manager/issues/20

I am also using Hyperion workspace

**Comment by rednaxela-alexander** [comment]
yes @rajneesh75 , i am using hyperion workspace too, and i can add new remote servers but the menus doesn't work, all the users in the company have the same issue and the solution that we found is downgrade firefox to 49 version and works perfectly, did you found other solution??

**Comment by rajneesh75** [comment]
My issue is that remote servers are not getting saved once I restart Firefox. But I guess, that's my individual issue as I noticed that Firefox is also not saving some other settings like pop ups. I tried deleting profiles, reinstalling Firefox but nothing worked for me. I have still not found reason/solution for it.

I am using firefox version 50.1.0 and Hyperion version 11.1.2.3.500 and did not encounter any issue with menus.  Which Hyperion version are you on. You may also try to see how workspace works with Firefox 64 bit developer edition and Mozilla Seamonkey.

**Comment by mibaker1** [comment]
I'm seeing the exact same issue as @rednaxela-alexander - we just pushed Firefox 50.1.0 to all users and none of the drop down menus in our Hyperion applications work now. Note that they *were* working for me until I forcibly uninstalled Remote XUL Manager then re-installed it (did this as a test because some new users I setup to use Firefox + Hyperion ran into the menu issue, so tried to see if I could replicate on my end). So maybe something with the install process for 50.1.0? I don't know .. for Hyperion we are on version 11.1.2.3.500 and also have an environment on 11.1.2.1.000 - same issue for both.

**Comment by rednaxela-alexander** [comment]
Hi, i'm using Hyperion version 11.1.2.3.000, so we try using SeaMonkey and it is working correctly, but with Firefox still have the same issue in 50 version, only in 49 and older version works perfectly

**Comment by jvillalobos** [comment]
Can you please confirm if you can successfully open [this page](https://developer.mozilla.org/samples/xultu/examples/aligner.xul) in the same systems (after giving developer.mozilla.org permission)?

**Comment by rajneesh75** [comment]
I get this message on browser

Remote XUL

This page uses an unsupported technology that is no longer available by default in Firefox.

    Please contact the website owners to inform them of this problem.

**Comment by jvillalobos** [comment]
And you added `https://developer.mozilla.org` to the allow list?

**Comment by rajneesh75** [comment]
sorry about my previous post. Yes the page is working after adding the url to whitelist

**Comment by jvillalobos** [comment]
Okay, thanks. That mostly confirms that the problem is probably related to a change in Firefox regarding XUL rather than something in the add-on. It would be good to see if there are Hyperion updates available, or if there's a way to report this problem to them.

**Comment by rednaxela-alexander** [comment]
Hello @jvillalobos i try open the link that you post and it opens successfully, but the drop list doesn't work, i can't change the values i'm adding a screenshot

![screen](https://cloud.githubusercontent.com/assets/24280432/21817765/eaeee59c-d72a-11e6-93d4-e0d484df839c.jpg)

**Comment by rajneesh75** [comment]
Working for me

![capture](https://cloud.githubusercontent.com/assets/14825844/21828049/f939514a-d753-11e6-9c22-45f997636089.PNG)

![capture1](https://cloud.githubusercontent.com/assets/14825844/21828100/4e57ccc4-d754-11e6-87c0-f286991473f4.PNG)

**Comment by rajneesh75** [comment]
Please take a look at this post
https://community.oracle.com/thread/4006078

**Comment by jvillalobos** [comment]
Thanks for the post. Given that there's a new version of the software that should work without remote XUL, I don't think there's anything left to do here.
